name: Python Tests
on:
  push:
    paths:
      - 'python/**'

jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - run: pip install -r python/requirements.txt
      
      - run: PYTHONPATH=. pytest
        working-directory: python
